<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"社区管理员管理",
                        "menuJump":"列表",
                        "tableName":"shequguanliyuan"
                    }
                ],
                "menu":"社区管理员管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"服务人员管理",
                        "menuJump":"列表",
                        "tableName":"fuwurenyuan"
                    }
                ],
                "menu":"服务人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医疗保险管理",
                        "menuJump":"列表",
                        "tableName":"yiliaobaoxian"
                    }
                ],
                "menu":"医疗保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"关怀服务管理",
                        "menuJump":"列表",
                        "tableName":"guanhuaifuwu"
                    }
                ],
                "menu":"关怀服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"身体状况管理",
                        "menuJump":"列表",
                        "tableName":"shentizhuangkuang"
                    }
                ],
                "menu":"身体状况管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"服务人员管理",
                        "menuJump":"列表",
                        "tableName":"fuwurenyuan"
                    }
                ],
                "menu":"服务人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医疗保险管理",
                        "menuJump":"列表",
                        "tableName":"yiliaobaoxian"
                    }
                ],
                "menu":"医疗保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"关怀服务管理",
                        "menuJump":"列表",
                        "tableName":"guanhuaifuwu"
                    }
                ],
                "menu":"关怀服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"身体状况管理",
                        "menuJump":"列表",
                        "tableName":"shentizhuangkuang"
                    }
                ],
                "menu":"身体状况管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"社区管理员",
        "tableName":"shequguanliyuan"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老人管理",
                        "menuJump":"列表",
                        "tableName":"laoren"
                    }
                ],
                "menu":"老人管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医疗保险管理",
                        "menuJump":"列表",
                        "tableName":"yiliaobaoxian"
                    }
                ],
                "menu":"医疗保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改"
                        ],
                        "menu":"关怀服务管理",
                        "menuJump":"列表",
                        "tableName":"guanhuaifuwu"
                    }
                ],
                "menu":"关怀服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"身体状况管理",
                        "menuJump":"列表",
                        "tableName":"shentizhuangkuang"
                    }
                ],
                "menu":"身体状况管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"服务人员",
        "tableName":"fuwurenyuan"
    },
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医疗保险管理",
                        "menuJump":"列表",
                        "tableName":"yiliaobaoxian"
                    }
                ],
                "menu":"医疗保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"关怀服务管理",
                        "menuJump":"列表",
                        "tableName":"guanhuaifuwu"
                    }
                ],
                "menu":"关怀服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"身体状况管理",
                        "menuJump":"列表",
                        "tableName":"shentizhuangkuang"
                    }
                ],
                "menu":"身体状况管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"老人",
        "tableName":"laoren"
    }
];

var hasMessage = '';
